version: '2'
services:
  spring-angular-app:
    depends_on:
      - postgres
    build: .
    ports:
      - 8080:8080
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test
volumes:
  postgres: